apiVersion: v1
kind: Service
metadata:
  name: browser-use
  namespace: browser-use
  labels:
    app.kubernetes.io/name: browser-use
    app.kubernetes.io/component: extraction-service
    app.kubernetes.io/managed-by: kubectl
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: browser-use
    app.kubernetes.io/component: extraction-service-light
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
